[tox]
isolated_build = True
env_list =
    py{311,312,313,314}-django52
    py{312,313,314}-django60

[pytest]
django_find_project = false
DJANGO_SETTINGS_MODULE = tests.settings
addopts = --doctest-modules
testpaths =
    tests
    ddrr

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
    django52: django52
    django60: django60
extras = xml
commands =
    pytest --color=no --import-mode importlib
