[tox]
isolated_build = True
env_list =
    py{311,312,313,314}-django52
    py{312,313,314}-django60

[pytest]
django_find_project = false
DJANGO_SETTINGS_MODULE = tests.settings
addopts = --doctest-modules
pythonpath = .
testpaths = tests

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
extras = xml
commands =
    pytest --color=no --import-mode importlib
setenv =
    PYTHONPATH = {toxinidir}:{env:PYTHONPATH:}

[testenv:py311-django52]
dependency_groups =
    {[testenv]dependency_groups}
    django52
commands_pre =
    python -m django --version
    python --version
[testenv:py312-django52]
dependency_groups = {[testenv:py311-django52]dependency_groups}
commands_pre = {[testenv:py311-django52]commands_pre}
[testenv:py313-django52]
dependency_groups = {[testenv:py311-django52]dependency_groups}
commands_pre = {[testenv:py311-django52]commands_pre}
[testenv:py314-django52]
dependency_groups = {[testenv:py311-django52]dependency_groups}
commands_pre = {[testenv:py311-django52]commands_pre}

[testenv:py312-django60]
dependency_groups =
    {[testenv]dependency_groups}
    django60
commands_pre =
    python -m django --version
    python --version
[testenv:py313-django60]
dependency_groups = {[testenv:py312-django60]dependency_groups}
commands_pre = {[testenv:py312-django60]commands_pre}
[testenv:py314-django60]
dependency_groups = {[testenv:py312-django60]dependency_groups}
commands_pre = {[testenv:py312-django60]commands_pre}
