[tox]
isolated_build = True
env_list =
    py{38,39,310}-django32
    py{38,39,310}-django40
    py{38,39,310,311}-django41

[pytest]
django_find_project = false
DJANGO_SETTINGS_MODULE = tests.settings
addopts = --doctest-modules
pythonpath = .
testpaths = tests

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
extras = xml
commands =
    pytest --color=no --import-mode importlib
setenv =
    PYTHONPATH = {toxinidir}:{env:PYTHONPATH:}

[testenv:py38-django32]
dependency_groups =
    {[testenv]dependency_groups}
    django32
commands_pre =
    python -m django --version
    python --version
[testenv:py39-django32]
dependency_groups = {[testenv:py38-django32]dependency_groups}
commands_pre = {[testenv:py38-django32]commands_pre}
[testenv:py310-django32]
dependency_groups = {[testenv:py38-django32]dependency_groups}
commands_pre = {[testenv:py38-django32]commands_pre}

[testenv:py38-django40]
dependency_groups =
    {[testenv]dependency_groups}
    django40
commands_pre =
    python -m django --version
    python --version
[testenv:py39-django40]
dependency_groups = {[testenv:py38-django40]dependency_groups}
commands_pre = {[testenv:py38-django40]commands_pre}
[testenv:py310-django40]
dependency_groups = {[testenv:py38-django40]dependency_groups}
commands_pre = {[testenv:py38-django40]commands_pre}

[testenv:py38-django41]
dependency_groups =
    {[testenv]dependency_groups}
    django41
commands_pre =
    python -m django --version
    python --version
[testenv:py39-django41]
dependency_groups = {[testenv:py38-django41]dependency_groups}
commands_pre = {[testenv:py38-django41]commands_pre}
[testenv:py310-django41]
dependency_groups = {[testenv:py38-django41]dependency_groups}
commands_pre = {[testenv:py38-django41]commands_pre}
[testenv:py311-django41]
dependency_groups = {[testenv:py38-django41]dependency_groups}
commands_pre = {[testenv:py38-django41]commands_pre}
