### =============================================================
### This configuration file is used by CircleCI build server
### https://circleci.com/docs/config-sample
### =============================================================

version: 2

jobs:
  build:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: pip install poetry
      - run: tox
